---

- hosts: servers
  remote_user: root
  gather_facts: false
  tasks:
    - name: check reachable
      ping:
    
    - name: install yum dependencies
      yum:
        name:
          - yum-utils
          - vim
          - wget
          - curl
        state: present
    
    - name: setup consul yum repo link
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    
    - name: install consul packages
      yum:
        name: consul
        state: present
    
    - name: create consul config folder
      file:
        path: /root/consul.d/{{ item }}
        state: directory
      with_items:
        - conf.d
        - data.d

    - name: create web service configuration
      template:
        src: ./templates/webservice.json.j2
        dest: /root/consul.d/conf.d/{{ item }}.json
      vars:
        service_name: "{{ item }}-80"
        service_port: 80
        service_tags: "web-server"
        service_ip: "{{ item }}"
        interval: 5
      with_items: "{{ groups['web_servers'] }}"
